ClasseComptable.insert(intitule: 'Provisions, avances, subventions et emprunts', numero: '1')
ClasseComptable.insert(intitule: 'Copropriétaires et tiers', numero: '4')
ClasseComptable.insert(intitule: 'Comptes financiers', numero: '5')
ClasseComptable.insert(intitule: 'Comptes de charges', numero: '6')
ClasseComptable.insert(intitule: 'Comptes de produits', numero: '7')
SousClasseComptable.insert(intitule: 'Provisions et avances', numero: '10')
SousClasseComptable.insert(intitule: 'Solde en attente sur travaux et opérations exceptionnelles', numero: '12')
SousClasseComptable.insert(intitule: 'Travaux décidés par l\'assemblée générale', numero: '12-1')
SousClasseComptable.insert(intitule: 'Travaux délégués au conseil syndical en application de l\'article 21-1 de la loi susvisée', numero: '12-2')
SousClasseComptable.insert(intitule: 'Subventions', numero: '13')
SousClasseComptable.insert(intitule: 'Fournisseurs', numero: '40')
SousClasseComptable.insert(intitule: 'Personnel', numero: '42')
SousClasseComptable.insert(intitule: 'Sécurité sociale et autres organismes sociaux', numero: '43')
SousClasseComptable.insert(intitule: 'Etat et collectivités territoriales', numero: '44')
SousClasseComptable.insert(intitule: 'Collectivité des copropriétaires', numero: '45')
SousClasseComptable.insert(intitule: 'Débiteurs et créditeurs divers', numero: '46')
SousClasseComptable.insert(intitule: 'Compte d\'attente', numero: '47')
SousClasseComptable.insert(intitule: 'Compte de régularisation', numero: '48')
SousClasseComptable.insert(intitule: 'Dépréciation des comptes de tiers', numero: '49')
SousClasseComptable.insert(intitule: 'Fonds placés', numero: '50')
SousClasseComptable.insert(intitule: 'Banques, ou fonds disponibles en banque pour le syndicat', numero: '51')
SousClasseComptable.insert(intitule: 'Caisse', numero: '53')
SousClasseComptable.insert(intitule: 'Achats de matières et fournitures', numero: '60')
SousClasseComptable.insert(intitule: 'Services extérieurs', numero: '61')
SousClasseComptable.insert(intitule: 'Frais d\'administration et honoraires', numero: '62')
SousClasseComptable.insert(intitule: 'Impôts - taxes et versements assimilés', numero: '63')
SousClasseComptable.insert(intitule: 'Frais de personnel', numero: '64')
SousClasseComptable.insert(intitule: 'Montant spécifique alloué au conseil syndical, au sein du budget prévisionnel, pour l\'exercice de sa délégation de pouvoirs en application de l\'article 21-1', numero: '65')
SousClasseComptable.insert(intitule: 'Charges financières des emprunts, agios ou autres', numero: '66')
SousClasseComptable.insert(intitule: 'Charges pour travaux et opérations exceptionnelles', numero: '67')
SousClasseComptable.insert(intitule: 'Dotations aux dépréciations sur créances douteuses', numero: '68')
SousClasseComptable.insert(intitule: 'Appels de fonds', numero: '70')
SousClasseComptable.insert(intitule: 'Autres produits', numero: '71')
SousClasseComptable.insert(intitule: 'Reprises de dépréciations de créances douteuses', numero: '78')
Compte.insert(intitule: 'Provisions pour travaux décidés', numero: '102')
Compte.insert(intitule: 'Avances', numero: '103')
Compte.insert(intitule: 'Avances de trésorerie', numero: '1031')
Compte.insert(intitule: 'Autres avances', numero: '1033')
Compte.insert(intitule: 'Fonds de travaux', numero: '105')
Compte.insert(intitule: 'Provisions pour travaux au titre de la délégation de pouvoirs accordée au conseil syndical en application de l\'article 21-1 de la loi susvisée', numero: '106')
Compte.insert(intitule: 'Subventions accordées en instance de versement', numero: '130')
Compte.insert(intitule: 'Factures parvenues', numero: '401')
Compte.insert(intitule: 'Factures non parvenues', numero: '408')
Compte.insert(intitule: 'Fournisseurs débiteurs', numero: '409')
Compte.insert(intitule: 'Rémunérations dues', numero: '421')
Compte.insert(intitule: 'Sécurité sociale', numero: '431')
Compte.insert(intitule: 'Autres organismes sociaux', numero: '432')
Compte.insert(intitule: 'Etat et autres organismes - subventions à recevoir', numero: '441')
Compte.insert(intitule: 'Etat - impôts et versements assimilés', numero: '442')
Compte.insert(intitule: 'Collectivités territoriales - aides', numero: '443')
Compte.insert(intitule: 'Copropriétaire individualisé', numero: '450')
Compte.insert(intitule: 'Copropriétaire - budget prévisionnel', numero: '450-1')
Compte.insert(intitule: 'Copropriétaire - travaux de l\'article 14-2 de la loi susvisée et opérations exceptionnelles', numero: '450-2')
Compte.insert(intitule: 'Copropriétaire - avances', numero: '450-3')
Compte.insert(intitule: 'Copropriétaire - emprunts', numero: '450-4')
Compte.insert(intitule: 'Copropriétaire-fonds de travaux', numero: '450-5')
Compte.insert(intitule: 'Copropriétaire - créances douteuses', numero: '459')
Compte.insert(intitule: 'Débiteurs divers', numero: '461')
Compte.insert(intitule: 'Créditeurs divers', numero: '462')
Compte.insert(intitule: 'Compte en attente d\'imputation débiteur', numero: '471')
Compte.insert(intitule: 'Compte en attente d\'imputation créditeur', numero: '472')
Compte.insert(intitule: 'Charges payées d\'avance', numero: '486')
Compte.insert(intitule: 'Produits encaissés d\'avance', numero: '487')
Compte.insert(intitule: 'Copropriétaires', numero: '491')
Compte.insert(intitule: 'Personnes autres que les copropriétaires', numero: '492')
Compte.insert(intitule: 'Compte à terme', numero: '501')
Compte.insert(intitule: 'Autre compte', numero: '502')
Compte.insert(intitule: 'Banques', numero: '512')
Compte.insert(intitule: 'Chèques postaux', numero: '514')
Compte.insert(intitule: 'Eau', numero: '601')
Compte.insert(intitule: 'Electricité', numero: '602')
Compte.insert(intitule: 'Chauffage, énergie et combustibles', numero: '603')
Compte.insert(intitule: 'Achats produits d\' entretien et petits équipements', numero: '604')
Compte.insert(intitule: 'Matériel', numero: '605')
Compte.insert(intitule: 'Fournitures', numero: '606')
Compte.insert(intitule: 'Nettoyage des locaux', numero: '611')
Compte.insert(intitule: 'Locations immobilières', numero: '612')
Compte.insert(intitule: 'Locations mobilières', numero: '613')
Compte.insert(intitule: 'Contrats de maintenance', numero: '614')
Compte.insert(intitule: 'Entretien et petites réparations', numero: '615')
Compte.insert(intitule: 'Primes d\'assurances', numero: '616')
Compte.insert(intitule: 'Rémunérations du syndic sur gestion copropriété', numero: '621')
Compte.insert(intitule: 'Rémunération du syndic', numero: '6211')
Compte.insert(intitule: 'Débours', numero: '6212')
Compte.insert(intitule: 'Frais postaux', numero: '6213')
Compte.insert(intitule: 'Autres honoraires du syndic', numero: '622')
Compte.insert(intitule: 'Honoraires travaux', numero: '6221')
Compte.insert(intitule: 'Prestations particulières', numero: '6222')
Compte.insert(intitule: 'Autres honoraires', numero: '6223')
Compte.insert(intitule: 'Rémunérations de tiers intervenants', numero: '623')
Compte.insert(intitule: 'Frais du conseil syndical', numero: '624')
Compte.insert(intitule: 'Taxe de balayage', numero: '632')
Compte.insert(intitule: 'Taxe foncière', numero: '633')
Compte.insert(intitule: 'Autres impôts et taxes', numero: '634')
Compte.insert(intitule: 'Salaires', numero: '641')
Compte.insert(intitule: 'Charges sociales et organismes sociaux', numero: '642')
Compte.insert(intitule: 'Taxe sur les salaires', numero: '643')
Compte.insert(intitule: 'Autres (médecine du travail, mutuelles, etc.)', numero: '644')
Compte.insert(intitule: 'Remboursement d\'annuités d\'emprunt', numero: '661')
Compte.insert(intitule: 'Autres charges financières et agios', numero: '662')
Compte.insert(intitule: 'Travaux décidés par l\'assemblée générale', numero: '671')
Compte.insert(intitule: 'Travaux urgents', numero: '672')
Compte.insert(intitule: 'Etudes techniques, diagnostic, consultation', numero: '673')
Compte.insert(intitule: 'Travaux délégués au conseil syndical en application de l\'article 21-1 de la loi susvisée', numero: '674')
Compte.insert(intitule: 'Pertes sur créances irrécouvrables', numero: '677')
Compte.insert(intitule: 'Charges exceptionnelles', numero: '678')
Compte.insert(intitule: 'Provisions sur opérations courantes', numero: '701')
Compte.insert(intitule: 'Provisions sur travaux du I de l\'article 14-2 et opérations exceptionnelles', numero: '702')
Compte.insert(intitule: 'Avances', numero: '703')
Compte.insert(intitule: 'Remboursements d\'annuités d\'emprunts', numero: '704')
Compte.insert(intitule: 'Affectation du fonds de travaux', numero: '705')
Compte.insert(intitule: 'Provisions au titre de la délégation de pouvoirs accordée au conseil syndical en application de l\'article 21-1 de la loi susvisée', numero: '706')
Compte.insert(intitule: 'Provisions sur opérations courantes', numero: '706-1')
Compte.insert(intitule: 'Provisions sur travaux et opérations exceptionnelles', numero: '706-2')
Compte.insert(intitule: 'Subventions', numero: '711')
Compte.insert(intitule: 'Emprunts', numero: '712')
Compte.insert(intitule: 'Indemnités d\'assurances', numero: '713')
Compte.insert(intitule: 'Produits divers (dont intérêts légaux dus par les copropriétaires)', numero: '714')
Compte.insert(intitule: 'Produits financiers', numero: '716')
Compte.insert(intitule: 'Produits exceptionnels', numero: '718')
