Classe_comptable.insert(:intitule => 'Provisions, avances, subventions et emprunts', :numero => '1')  
Classe_comptable.insert(:intitule => 'Copropriétaires et tiers', :numero => '4')                      
Classe_comptable.insert(:intitule => 'Comptes financiers', :numero => '5')                             
Classe_comptable.insert(:intitule => 'Comptes de charges', :numero => '6')                            
Classe_comptable.insert(:intitule => 'Comptes de produits', :numero => '7')                           
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Provisions, avances, subventions et emprunts').get(:id), :intitule => 'Provisions et avances', :numero => '10')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Provisions, avances, subventions et emprunts').get(:id)  , :intitule => 'Solde en attente sur travaux et opérations exceptionnelles', :numero => '12')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Provisions, avances, subventions et emprunts').get(:id)  , :intitule => 'Travaux décidés par l\'assemblée générale', :numero => '12-1')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Provisions, avances, subventions et emprunts').get(:id)  , :intitule => 'Travaux délégués au conseil syndical en application de l\'article 21-1 de la loi susvisée', :numero => '12-2')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Provisions, avances, subventions et emprunts').get(:id)  , :intitule => 'Subventions', :numero => '13')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Copropriétaires et tiers').get(:id), :intitule => 'Fournisseurs', :numero => '40')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Copropriétaires et tiers').get(:id), :intitule => 'Personnel', :numero => '42')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Copropriétaires et tiers').get(:id), :intitule => 'Sécurité sociale et autres organismes sociaux', :numero => '43')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Copropriétaires et tiers').get(:id), :intitule => 'Etat et collectivités territoriales', :numero => '44')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Copropriétaires et tiers').get(:id), :intitule => 'Collectivité des copropriétaires', :numero => '45')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Copropriétaires et tiers').get(:id), :intitule => 'Débiteurs et créditeurs divers', :numero => '46')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Copropriétaires et tiers').get(:id), :intitule => 'Compte d\'attente', :numero => '47')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Copropriétaires et tiers').get(:id), :intitule => 'Compte de régularisation', :numero => '48')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Copropriétaires et tiers').get(:id), :intitule => 'Dépréciation des comptes de tiers', :numero => '49')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Comptes financiers').get(:id), :intitule => 'Fonds placés', :numero => '50')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Comptes financiers').get(:id), :intitule => 'Banques, ou fonds disponibles en banque pour le syndicat', :numero => '51')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Comptes financiers').get(:id), :intitule => 'Caisse', :numero => '53')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Comptes de charges').get(:id), :intitule => 'Achats de matières et fournitures', :numero => '60')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Comptes de charges').get(:id), :intitule => 'Services extérieurs', :numero => '61')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Comptes de charges').get(:id), :intitule => 'Frais d\'administration et honoraires', :numero => '62')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Comptes de charges').get(:id), :intitule => 'Impôts - taxes et versements assimilés', :numero => '63')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Comptes de charges').get(:id), :intitule => 'Frais de personnel', :numero => '64')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Comptes de charges').get(:id), :intitule => 'Montant spécifique alloué au conseil syndical, au sein du budget prévisionnel, pour l\'exercice de sa délégation de pouvoirs en application de l\'article 21-1', :numero => '65')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Comptes de charges').get(:id), :intitule => 'Charges financières des emprunts, agios ou autres', :numero => '66')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Comptes de charges').get(:id), :intitule => 'Charges pour travaux et opérations exceptionnelles', :numero => '67')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Comptes de charges').get(:id), :intitule => 'Dotations aux dépréciations sur créances douteuses', :numero => '68')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Comptes de produits').get(:id), :intitule => 'Appels de fonds', :numero => '70')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Comptes de produits').get(:id), :intitule => 'Autres produits', :numero => '71')
Sous_classe_comptable.insert(:classe_comptable_id => Classe_comptable.where(:intitule => 'Comptes de produits').get(:id), :intitule => 'Reprises de dépréciations de créances douteuses', :numero => '78')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Provisions et avances').get(:id), :intitule => 'Provisions pour travaux décidés', :numero => '102')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Provisions et avances').get(:id), :intitule => 'Avances', :numero => '103')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Provisions et avances').get(:id), :intitule => 'Avances de trésorerie', :numero => '1031')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Provisions et avances').get(:id), :intitule => 'Autres avances', :numero => '1033')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Provisions et avances').get(:id), :intitule => 'Fonds de travaux', :numero => '105')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Provisions et avances').get(:id), :intitule => 'Provisions pour travaux au titre de la délégation de pouvoirs accordée au conseil syndical en application de l\'article 21-1 de la loi susvisée', :numero => '106')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Subventions').get(:id), :intitule => 'Subventions accordées en instance de versement', :numero => '130')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Fournisseurs').get(:id), :intitule => 'Factures parvenues', :numero => '401')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Fournisseurs').get(:id), :intitule => 'Factures non parvenues', :numero => '408')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Fournisseurs').get(:id), :intitule => 'Fournisseurs débiteurs', :numero => '409')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Personnel').get(:id), :intitule => 'Rémunérations dues', :numero => '421')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Sécurité sociale et autres organismes sociaux').get(:id), :intitule => 'Sécurité sociale', :numero => '431')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Sécurité sociale et autres organismes sociaux').get(:id), :intitule => 'Autres organismes sociaux', :numero => '432')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Etat et collectivités territoriales').get(:id), :intitule => 'Etat et autres organismes - subventions à recevoir', :numero => '441')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Etat et collectivités territoriales').get(:id), :intitule => 'Etat - impôts et versements assimilés', :numero => '442')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Etat et collectivités territoriales').get(:id), :intitule => 'Collectivités territoriales - aides', :numero => '443')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Collectivité des copropriétaires').get(:id), :intitule => 'Copropriétaire individualisé', :numero => '450')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Collectivité des copropriétaires').get(:id), :intitule => 'Copropriétaire - budget prévisionnel', :numero => '450-1')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Collectivité des copropriétaires').get(:id), :intitule => 'Copropriétaire - travaux de l\'article 14-2 de la loi susvisée et opérations exceptionnelles', :numero => '450-2')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Collectivité des copropriétaires').get(:id), :intitule => 'Copropriétaire - avances', :numero => '450-3')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Collectivité des copropriétaires').get(:id), :intitule => 'Copropriétaire - emprunts', :numero => '450-4')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Collectivité des copropriétaires').get(:id), :intitule => 'Copropriétaire-fonds de travaux', :numero => '450-5')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Collectivité des copropriétaires').get(:id), :intitule => 'Copropriétaire - créances douteuses', :numero => '459')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Débiteurs et créditeurs divers').get(:id), :intitule => 'Débiteurs divers', :numero => '461')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Débiteurs et créditeurs divers').get(:id), :intitule => 'Créditeurs divers', :numero => '462')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Compte d\'attente').get(:id), :intitule => 'Compte en attente d\'imputation débiteur', :numero => '471')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Compte d\'attente').get(:id), :intitule => 'Compte en attente d\'imputation créditeur', :numero => '472')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Compte de régularisation').get(:id), :intitule => 'Charges payées d\'avance', :numero => '486')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Compte de régularisation').get(:id), :intitule => 'Produits encaissés d\'avance', :numero => '487')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Dépréciation des comptes de tiers').get(:id), :intitule => 'Copropriétaires', :numero => '491')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Dépréciation des comptes de tiers').get(:id), :intitule => 'Personnes autres que les copropriétaires', :numero => '492')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Fonds placé').get(:id), :intitule => 'Compte à terme', :numero => '501')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Fonds placé').get(:id), :intitule => 'Autre compte', :numero => '502')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Banques, ou fonds disponibles en banque pour le syndicat').get(:id), :intitule => 'Banques', :numero => '512')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Banques, ou fonds disponibles en banque pour le syndicat').get(:id), :intitule => 'Chèques postaux', :numero => '514')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Achats de matières et fournitures').get(:id), :intitule => 'Eau', :numero => '601')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Achats de matières et fournitures').get(:id), :intitule => 'Electricité', :numero => '602')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Achats de matières et fournitures').get(:id), :intitule => 'Chauffage, énergie et combustibles', :numero => '603')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Achats de matières et fournitures').get(:id), :intitule => 'Achats produits d\' entretien et petits équipements', :numero => '604')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Achats de matières et fournitures').get(:id), :intitule => 'Matériel', :numero => '605')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Achats de matières et fournitures').get(:id), :intitule => 'Fournitures', :numero => '606')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Services extérieurs').get(:id), :intitule => 'Nettoyage des locaux', :numero => '611')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Services extérieurs').get(:id), :intitule => 'Locations immobilières', :numero => '612')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Services extérieurs').get(:id), :intitule => 'Locations mobilières', :numero => '613')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Services extérieurs').get(:id), :intitule => 'Contrats de maintenance', :numero => '614')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Services extérieurs').get(:id), :intitule => 'Entretien et petites réparations', :numero => '615')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Services extérieurs').get(:id), :intitule => 'Primes d\'assurances', :numero => '616')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Frais d\'administration et honoraires').get(:id), :intitule => 'Rémunérations du syndic sur gestion copropriété', :numero => '621')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Frais d\'administration et honoraires').get(:id), :intitule => 'Rémunération du syndic', :numero => '6211')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Frais d\'administration et honoraires').get(:id), :intitule => 'Débours', :numero => '6212')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Frais d\'administration et honoraires').get(:id), :intitule => 'Frais postaux', :numero => '6213')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Frais d\'administration et honoraires').get(:id), :intitule => 'Autres honoraires du syndic', :numero => '622')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Frais d\'administration et honoraires').get(:id), :intitule => 'Honoraires travaux', :numero => '6221')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Frais d\'administration et honoraires').get(:id), :intitule => 'Prestations particulières', :numero => '6222')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Frais d\'administration et honoraires').get(:id), :intitule => 'Autres honoraires', :numero => '6223')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Frais d\'administration et honoraires').get(:id), :intitule => 'Rémunérations de tiers intervenants', :numero => '623')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Frais d\'administration et honoraires').get(:id), :intitule => 'Frais du conseil syndical', :numero => '624')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Impôts - taxes et versements assimilés').get(:id), :intitule => 'Taxe de balayage', :numero => '632')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Impôts - taxes et versements assimilés').get(:id), :intitule => 'Taxe foncière', :numero => '633')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Impôts - taxes et versements assimilés').get(:id), :intitule => 'Autres impôts et taxes', :numero => '634')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Frais de personnel').get(:id), :intitule => 'Salaires', :numero => '641')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Frais de personnel').get(:id), :intitule => 'Charges sociales et organismes sociaux', :numero => '642')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Frais de personnel').get(:id), :intitule => 'Taxe sur les salaires', :numero => '643')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Frais de personnel').get(:id), :intitule => 'Autres (médecine du travail, mutuelles, etc.)', :numero => '644')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Charges financières des emprunts, agios ou autres').get(:id), :intitule => 'Remboursement d\'annuités d\'emprunt', :numero => '661')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Charges financières des emprunts, agios ou autres').get(:id), :intitule => 'Autres charges financières et agios', :numero => '662')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Charges pour travaux et opérations exceptionnelles').get(:id), :intitule => 'Travaux décidés par l\'assemblée générale', :numero => '671')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Charges pour travaux et opérations exceptionnelles').get(:id), :intitule => 'Travaux urgents', :numero => '672')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Charges pour travaux et opérations exceptionnelles').get(:id), :intitule => 'Etudes techniques, diagnostic, consultation', :numero => '673')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Charges pour travaux et opérations exceptionnelles').get(:id), :intitule => 'Travaux délégués au conseil syndical en application de l\'article 21-1 de la loi susvisée', :numero => '674')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Charges pour travaux et opérations exceptionnelles').get(:id), :intitule => 'Pertes sur créances irrécouvrables', :numero => '677')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Charges pour travaux et opérations exceptionnelles').get(:id), :intitule => 'Charges exceptionnelles', :numero => '678')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Appels de fonds').get(:id), :intitule => 'Provisions sur opérations courantes', :numero => '701')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Appels de fonds').get(:id), :intitule => 'Provisions sur travaux du I de l\'article 14-2 et opérations exceptionnelles', :numero => '702')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Appels de fonds').get(:id), :intitule => 'Avances', :numero => '703')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Appels de fonds').get(:id), :intitule => 'Remboursements d\'annuités d\'emprunts', :numero => '704')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Appels de fonds').get(:id), :intitule => 'Affectation du fonds de travaux', :numero => '705')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Appels de fonds').get(:id), :intitule => 'Provisions au titre de la délégation de pouvoirs accordée au conseil syndical en application de l\'article 21-1 de la loi susvisée', :numero => '706')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Appels de fonds').get(:id), :intitule => 'Provisions sur opérations courantes', :numero => '706-1')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Appels de fonds').get(:id), :intitule => 'Provisions sur travaux et opérations exceptionnelles', :numero => '706-2')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Autres produits').get(:id), :intitule => 'Subventions', :numero => '711')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Autres produits').get(:id), :intitule => 'Emprunts', :numero => '712')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Autres produits').get(:id), :intitule => 'Indemnités d\'assurances', :numero => '713')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Autres produits').get(:id), :intitule => 'Produits divers (dont intérêts légaux dus par les copropriétaires)', :numero => '714')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Autres produits').get(:id), :intitule => 'Produits financiers', :numero => '716')
Ligne_comptable.insert(:sous_classe_comptable_id => Sous_classe_comptable.where(:intitule) => 'Autres produits').get(:id), :intitule => 'Produits exceptionnels', :numero => '718')

